
const G={lang:"ms",avatar:"🧑‍💻",room:"",key:"",player:null,index:0,score:0,xp:0,start:0,lastRank:null,
avatars:["🧑‍💻","👩‍💻","🧑‍🔧","👩‍🔧","🦸","🦸‍♀️"],
palette:[["#55c7ff","#0877c9","#044e86"],["#ff7d7d","#d92f42","#861a27"],["#ffd565","#f08c00","#995600"],["#8ff5a5","#22a447","#11632a"],["#c79cff","#7948d8","#45257f"],["#fff","#a5b3c1","#59636c"],["#ff9fe2","#d936a7","#7e1c63"],["#84fff3","#18aaa0","#0c6660"],["#f2ff7e","#9aa917","#59630c"],["#ffb07b","#dc5b15","#80330d"]],
init(){avatarGrid.innerHTML=this.avatars.map((a,i)=>`<button class="avatar ${i===0?"selected":""}" data-a="${a}">${a}</button>`).join("");avatarGrid.onclick=e=>{if(!e.target.dataset.a)return;this.avatar=e.target.dataset.a;document.querySelectorAll(".avatar").forEach(x=>x.classList.toggle("selected",x===e.target))};bmBtn.onclick=()=>this.setLang("ms");enBtn.onclick=()=>this.setLang("en");joinBtn.onclick=()=>this.join();const q=new URLSearchParams(location.search).get("room");if(q)roomCode.value=q.toUpperCase()},
setLang(x){this.lang=x;SERVER_HERO_BYTE.setLanguage(x);bmBtn.classList.toggle("active",x==="ms");enBtn.classList.toggle("active",x==="en")},
async join(){const room=SERVER_HERO_MP.cleanRoom(roomCode.value),name=playerName.value.trim(),id=playerId.value.trim();if(!room||!name||!id){joinMsg.textContent=this.lang==="ms"?"Sila isi kod bilik, nama dan ID.":"Please enter room code, name and ID.";return}try{const r=await SERVER_HERO_MP.join(room,{name,id,avatar:this.avatar,language:this.lang});this.room=r.room;this.key=r.key;this.player={name,id,avatar:this.avatar};joinScreen.classList.add("hidden");waitingScreen.classList.remove("hidden");waitingInfo.textContent=`${name} • ${room}`;await SERVER_HERO_MP.watchPlayer(room,r.key,p=>{if(p?.approved&&p.status==="approved")waitingInfo.textContent=this.lang==="ms"?"✅ Diluluskan. Menunggu guru memulakan perlumbaan...":"✅ Approved. Waiting for the teacher to start..."});await SERVER_HERO_MP.watchRoom(room,data=>{if(data?.status==="racing"&&!waitingScreen.classList.contains("hidden"))this.startRace();if(data?.players)this.renderRace(data.players);if(data?.status==="finished"&&!gameScreen.classList.contains("hidden"))this.finish(data.players||{})})}catch(e){joinMsg.textContent="Tidak dapat menyambung ke bilik.";console.error(e)}},
startRace(){waitingScreen.classList.add("hidden");gameScreen.classList.remove("hidden");displayName.textContent=this.player.name;displayRoom.textContent=this.room;this.index=0;this.score=0;this.xp=0;this.showQuestion()},
showQuestion(){const q=SERVER_HERO_QUESTIONS[this.index];if(!q){SERVER_HERO_MP.updatePlayer(this.room,this.key,{finished:true,status:"finished"});questionArea.innerHTML="<h2>🏁 Menunggu keputusan akhir guru...</h2>";return}this.start=Date.now();questionArea.innerHTML=`<small>${this.lang==="ms"?"Soalan":"Question"} ${this.index+1}/${SERVER_HERO_QUESTIONS.length}</small><h2>${q.q[this.lang]}</h2><div class="answers">${q.options.map((o,i)=>`<button class="answer" data-i="${i}"><b>${String.fromCharCode(65+i)}.</b> ${o[this.lang]}</button>`).join("")}</div>`;questionArea.querySelectorAll(".answer").forEach(b=>b.onclick=()=>this.answer(Number(b.dataset.i),q,b))},
async answer(i,q,b){if(b.disabled)return;if(i!==q.answer){b.classList.add("wrong");setTimeout(()=>b.classList.remove("wrong"),700);SERVER_HERO_BYTE.show(q.bad[this.lang]);return}questionArea.querySelectorAll(".answer").forEach(x=>x.disabled=true);b.classList.add("correct");const sec=(Date.now()-this.start)/1000,gain=sec<=3?200:sec<=5?150:100;this.score+=gain;this.xp+=sec<=3?100:sec<=5?75:50;score.textContent=this.score;xp.textContent=this.xp;SERVER_HERO_BYTE.show(q.ok[this.lang]);await SERVER_HERO_MP.updatePlayer(this.room,this.key,{score:this.score,xp:this.xp,progress:this.index+1,status:"racing",lastAnswerMs:Math.round(sec*1000),turboUntil:Date.now()+(sec<=5?1200:0)});setTimeout(()=>{this.index++;this.showQuestion()},1500)},
renderRace(playersObj){const arr=Object.values(playersObj||{}).filter(p=>p.approved).sort((a,b)=>(b.score||0)-(a.score||0)||(a.lastAnswerMs||999999)-(b.lastAnswerMs||999999));const me=arr.findIndex(p=>p.key===this.key)+1;rank.textContent=me>0?`#${me}`:"#-";if(this.lastRank&&me>0&&me<this.lastRank)this.showOvertake(this.lastRank-me);if(me>0)this.lastRank=me;const now=Date.now();raceTrack.innerHTML=arr.slice(0,10).map((p,i)=>{const c=this.palette[i%this.palette.length],turbo=(p.turboUntil||0)>now;return `<div class="lane"><div class="car ${p.key===this.key?"player":""} ${turbo?"turbo":""}" style="left:${Math.min(88,(p.progress||0)/SERVER_HERO_QUESTIONS.length*88)}%;--car-light:${c[0]};--car:${c[1]};--car-dark:${c[2]}"><div class="race-car-body"><span class="wheel back"></span><span class="wheel front"></span></div><b>${i+1}. ${p.name}</b></div></div>`}).join("")},
showOvertake(n){document.querySelector(".overtake-badge")?.remove();const d=document.createElement("div");d.className="overtake-badge";d.textContent=this.lang==="ms"?`🚀 Anda memotong ${n} pemain!`:`🚀 You overtook ${n} player${n>1?"s":""}!`;document.body.appendChild(d);setTimeout(()=>d.remove(),1300)},
finish(playersObj){gameScreen.classList.add("hidden");resultScreen.classList.remove("hidden");const arr=Object.values(playersObj).filter(p=>p.approved).sort((a,b)=>(b.score||0)-(a.score||0)||(a.lastAnswerMs||999999)-(b.lastAnswerMs||999999));const pos=arr.findIndex(p=>p.key===this.key)+1;trophy.textContent=pos===1?"🏆":pos===2?"🥈":pos===3?"🥉":"🏁";finalRank.textContent=this.lang==="ms"?`Kedudukan #${pos} daripada ${arr.length}`:`Position #${pos} of ${arr.length}`;finalStats.textContent=`${this.lang==="ms"?"Markah":"Score"} ${this.score} • XP ${this.xp}`}};
document.addEventListener("DOMContentLoaded",()=>G.init());
